-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 11:42:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema copa_do_mundo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema copa_do_mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `copa_do_mundo` DEFAULT CHARACTER SET utf8 ;
USE `copa_do_mundo` ;

-- -----------------------------------------------------
-- Table `copa_do_mundo`.`selecoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`selecoes` (
  `id_selecao` INT NOT NULL AUTO_INCREMENT,
  `nome_selecao` VARCHAR(50) NOT NULL,
  `continente` VARCHAR(30) NOT NULL,
  `tecnico` VARCHAR(50) NOT NULL,
  `titulos` INT NOT NULL,
  PRIMARY KEY (`id_selecao`),
  UNIQUE INDEX `nome_selecao_UNIQUE` (`nome_selecao` ASC) VISIBLE,
  UNIQUE INDEX `tecnico_UNIQUE` (`tecnico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`jogadores` (
  `id_jogador` INT NOT NULL AUTO_INCREMENT,
  `nome_jogador` VARCHAR(60) NOT NULL,
  `posicao` VARCHAR(30) NOT NULL,
  `numero_camisa` INT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `id_selecao` INT NOT NULL,
  PRIMARY KEY (`id_jogador`),
  INDEX `fk_jogadores_selecoes_idx` (`id_selecao` ASC) VISIBLE,
  CONSTRAINT `id_selecao`
    FOREIGN KEY (`id_selecao`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`estadios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`estadios` (
  `id_estadio` INT NOT NULL AUTO_INCREMENT,
  `nome_estadio` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id_estadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`arbitros` (
  `id_arbitro` INT NOT NULL AUTO_INCREMENT,
  `nome_arbitro` VARCHAR(50) NOT NULL,
  `nacionalidade` VARCHAR(30) NOT NULL,
  `funcao` ENUM('Principal', 'Assistente', 'VAR') NOT NULL,
  PRIMARY KEY (`id_arbitro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_do_mundo`.`partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `copa_do_mundo`.`partidas` (
  `id_partida` INT NOT NULL AUTO_INCREMENT,
  `data_partida` DATE NOT NULL,
  `id_estadio` INT NOT NULL,
  `id_arbitro` INT NOT NULL,
  `id_selecao_1` INT NOT NULL,
  `id_selecao_2` INT NOT NULL,
  `quantidade_gols_selecao_1` INT NOT NULL,
  `quantidade_gols_selecao_2` INT NOT NULL,
  `vencedor` INT NULL,
  PRIMARY KEY (`id_partida`),
  INDEX `fk_partidas_selecoes1_idx` (`id_selecao_1` ASC) VISIBLE,
  INDEX `fk_partidas_selecoes3_idx` (`id_selecao_2` ASC) VISIBLE,
  INDEX `fk_partidas_selecoes2_idx` (`vencedor` ASC) VISIBLE,
  INDEX `fk_partidas_estadios1_idx` (`id_estadio` ASC) VISIBLE,
  INDEX `fk_partidas_arbitros1_idx` (`id_arbitro` ASC) VISIBLE,
  CONSTRAINT `fk_partidas_selecoes1`
    FOREIGN KEY (`id_selecao_1`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_partidas_selecoes3`
    FOREIGN KEY (`id_selecao_2`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_partidas_selecoes2`
    FOREIGN KEY (`vencedor`)
    REFERENCES `copa_do_mundo`.`selecoes` (`id_selecao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_partidas_estadios1`
    FOREIGN KEY (`id_estadio`)
    REFERENCES `copa_do_mundo`.`estadios` (`id_estadio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_partidas_arbitros1`
    FOREIGN KEY (`id_arbitro`)
    REFERENCES `copa_do_mundo`.`arbitros` (`id_arbitro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Criação do trigger que define automaticamente o vencedor da partida
DELIMITER $$

CREATE TRIGGER trg_definir_vencedor
BEFORE INSERT ON partidas
FOR EACH ROW
BEGIN
    IF NEW.quantidade_gols_selecao_1 > NEW.quantidade_gols_selecao_2 THEN
        SET NEW.vencedor = NEW.id_selecao_1;
    ELSEIF NEW.quantidade_gols_selecao_2 > NEW.quantidade_gols_selecao_1 THEN
        SET NEW.vencedor = NEW.id_selecao_2;
    ELSE
        SET NEW.vencedor = NULL; -- Indica empate
    END IF;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER trg_valida_arbitro_principal
BEFORE INSERT ON partidas
FOR EACH ROW
BEGIN
    DECLARE v_funcao VARCHAR(30);
    SELECT funcao INTO v_funcao 
    FROM arbitros 
    WHERE id_arbitro = NEW.id_arbitro;
    IF v_funcao != 'Principal' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Operação bloqueada: Apenas árbitros com a função "Principal" podem ser alocados na partida.';
    END IF;
END$$

DELIMITER ;

-- Inserção na tabela estadios
INSERT INTO estadios (nome_estadio, cidade, pais, capacidade) VALUES 
('MetLife Stadium', 'Nova Jersey', 'Estados Unidos', 82500),
('Estádio Azteca', 'Cidade do México', 'México', 87523),
('SoFi Stadium', 'Los Angeles', 'Estados Unidos', 70240),
('BMO Field', 'Toronto', 'Canadá', 30000);

-- Inserção na tabela selecoes
INSERT INTO selecoes (nome_selecao, continente, tecnico, titulos) VALUES 
('Brasil', 'América do Sul', 'Dorival Júnior', 5),
('França', 'Europa', 'Didier Deschamps', 2),
('Argentina', 'América do Sul', 'Lionel Scaloni', 3),
('Estados Unidos', 'América do Norte', 'Gregg Berhalter', 0);

-- Inserção na tabela jogadores
INSERT INTO jogadores (nome_jogador, posicao, numero_camisa, data_nascimento, id_selecao) VALUES 
('Vinícius Júnior', 'Atacante', 7, '2000-07-12', 1),
('Endrick', 'Atacante', 9, '2006-07-21', 1),
('Kylian Mbappé', 'Atacante', 10, '1998-12-20', 2),
('Eduardo Camavinga', 'Meio-campo', 6, '2002-11-10', 2),
('Lionel Messi', 'Atacante', 10, '1987-06-24', 3),
('Christian Pulisic', 'Atacante', 10, '1998-09-18', 4);

-- Inserção na tabela arbitros (3 Principais, 3 Assistentes, 2 VAR)
INSERT INTO arbitros (nome_arbitro, nacionalidade, funcao) VALUES 
('Wilton Pereira Sampaio', 'Brasil', 'Principal'), -- ID 1
('Daniele Orsato', 'Itália', 'Principal'), -- ID 2
('Szymon Marciniak', 'Polônia', 'Principal'), -- ID 3
('Neuza Back', 'Brasil', 'Assistente'), -- ID 4
('Ciro Carbone', 'Itália', 'Assistente'), -- ID 5
('Tomasz Listkiewicz', 'Polônia', 'Assistente'), -- ID 6
('Pol van Boekel', 'Holanda', 'VAR'), -- ID 7
('Mauro Vigliano', 'Argentina', 'VAR'); -- ID 8

-- Inserção na tabela partidas com a ordem corrigida das colunas
INSERT INTO partidas (data_partida, id_estadio, id_arbitro, id_selecao_1, id_selecao_2, quantidade_gols_selecao_1, quantidade_gols_selecao_2, vencedor) VALUES 
('2026-06-15', 3, 1, 1, 4, 3, 1, 1),
('2026-06-18', 1, 2, 2, 3, 2, 2, NULL), -- Empate no MetLife Stadium
('2026-06-22', 2, 3, 1, 3, 2, 1, 1); 



-- Consulta bônus 1: Total de jogadores cadastrados por seleção 
SELECT s.nome_selecao AS Selecao, COUNT(j.id_jogador) AS Total_Jogadores
FROM selecoes s
LEFT JOIN jogadores j ON s.id_selecao = j.id_selecao
GROUP BY s.id_selecao, s.nome_selecao
ORDER BY Total_Jogadores DESC;

-- Consulta bônus 2: Média de capacidade dos estádios por país 
SELECT pais, COUNT(id_estadio) AS qtd_estadios, ROUND(AVG(capacidade), 0) AS media_capacidade
FROM estadios
GROUP BY pais;




-- Tentar cadastrar um jogador em uma seleção que NÃO existe (ID 999)
-- O MySQL DEVE barrar e exibir um erro de Foreign Key
---INSERT INTO jogadores (nome_jogador, posicao, numero_camisa, data_nascimento, id_selecao) 
---VALUES ('Jogador Fantasma', 'Atacante', 99, '2000-01-01', 999);